Move logging to the celery task for sync
hypothesis/h pull request #6343
Opened 2020-10-20 19:07 UTC by jon-betts

This ties up a couple of things that were niggling me:

 * We don't use a celery task logger in the middle of the service any more
 * We test the counting behavior in isolation from the logging behavior
 * We test the counting more directly

2020-10-20 19:10 UTC, jon-betts commented on h/services/search_index/_queue.py
> +        FORCED = "Annotations synced because their jobs had force=True"
Made this enum like, but not actually an enum, as that prints out a little weird. Still legible, but not as nice.

Nesting it in like this is a Java like trick, and means you can access the enum wherever the `Queue` goes. This is convenient for the caller as it's usually them that want to make comparisons with the values (although we don't actually use if for that here)

2020-10-20 19:10 UTC, jon-betts commented on h/services/search_index/service.py
> +TASK_LOGGER = get_task_logger(__name__)
I think this makes more sense

2020-10-21 14:59 UTC, seanh requested changes

2020-10-21 14:59 UTC, seanh commented on tests/h/tasks/indexer_test.py
> +        print(caplog.text)
```suggestion
```

2020-10-21 17:46 UTC, seanh approved these changes

2020-10-21 17:48 UTC, merged