Fix pylint's too-few-public-methods
hypothesis/h pull request #6817
Opened 2021-07-14 13:14 UTC by marcospri

2021-07-14 13:15 UTC, marcospri commented on h/models/feature_cohort.py
> -    def __init__(self, name):
I don't think this is necessary in a model.

2021-07-15 11:46 UTC, marcospri commented on h/models/feature_cohort.py
> -    def __init__(self, name):
I also think this is third PR where I found it and removed it.

2021-07-15 12:10 UTC, jon-betts requested changes
We've discussed this before, and you might want to get @seanh's take as well, but I think we should globally disable this warning.

Honestly it's just part of our coding style that we don't care about this. We often use objects as a way to collect functionality together and expose a single method on something. Or any other number of times it's perfectly reasonable.

2021-07-15 14:15 UTC, marcospri commented
> We've discussed this before, and you might want to get @seanh's take as well, but I think we should globally disable this warning.
> 
> Honestly it's just part of our coding style that we don't care about this. We often use objects as a way to collect functionality together and expose a single method on something. Or any other number of times it's perfectly reasonable.

I was thinking "this is bullshit" halfway in but was too invested to add the rule to pylintrc then! (jk, its pretty straightforward to add them)

2021-07-16 09:17 UTC, marcospri commented on .pylintrc
> +        too-few-public-methods
This is the change that matches the original PR scope but added the rest of the config change here too.

2021-07-16 12:31 UTC, jon-betts approved these changes

2021-07-16 14:20 UTC, merged