Fix pylint unused-argument on the test code
hypothesis/h pull request #6953
Opened 2021-08-12 16:10 UTC by marcospri

Enabling rules that were disabled in `pylintrc`, fixing some of them and also many disable inlines.

2021-08-13 15:34 UTC, marcospri commented on h/schemas/annotation.py
> -
Found by the duplicate-code rule but this one was not used anywhere so it was an easy fix

2021-08-17 10:47 UTC, jon-betts requested changes
I'm stopping this review a bit early as it's very long and I've spotted some repeated patterns already that probably could do with a going through in a more fine grained way.

There are a number of fixtures which have moved out of the arguments and into `usefixtures` which shouldn't generally effect the test they are attached to: e.g. `factories`, `matchers` and `db_session`. This makes me wonder about the others and whether these arguments are needed at all. It's extremely common that our tests include fixtures that are just irrelevant to the test.

I think we might be working around the warning here, but not really getting at what the warning is trying to tell us. It makes tests more confusing if you have to try to prove a negative about why including something that doesn't matter is important.

Seeing as this is complicated, I'd suggest not tackling this in with so many other different lint fixes at once.

When it comes to un-used arguments I think we should be asking:

 * Does the test pass without the argument at all?
 * If this is being attached to many tests should the test be `autouse=True` (if defined locally) or `usefixtures` at the class level if not?

2021-08-17 10:47 UTC, jon-betts commented on tests/.pylintrc
> +    no-member, #  Intermittent failures with the same input
Yeah... fair enough.

2021-08-17 10:47 UTC, jon-betts commented on tests/functional/test_oauth.py
> +    def test_request_fails_if_access_token_expired(self, app, db_session, factories):
:+1: These are much better

2021-08-17 10:47 UTC, jon-betts commented on tests/h/feeds/atom_test.py
>          return "annotation url"
This one looks like an odd one out from the `lamdba` solutions below

2021-08-17 10:47 UTC, jon-betts commented on tests/h/models/group_scope_test.py
> +    @pytest.mark.usefixtures("db_session")
```suggestion
```
? The DB session is going to be around regardless here I think

2021-08-17 10:47 UTC, jon-betts commented on tests/h/models/group_scope_test.py
> +    @pytest.mark.usefixtures("matchers")
```suggestion
```
I think the matchers are comparators. If we aren't using them it probably doesn't need to be here

2021-08-17 10:47 UTC, jon-betts commented on tests/h/models/organization_test.py
> +@pytest.mark.usefixtures("db_session", "factories")
```suggestion
```

2021-08-17 10:47 UTC, jon-betts commented on tests/h/models/user_identity_test.py
> +    @pytest.mark.usefixtures("matchers")
```suggestion
```

2021-08-17 10:47 UTC, jon-betts commented on tests/h/oauth/jwt_grant_test.py
> +    @pytest.mark.usefixtures("db_session")
```suggestion
```

2021-08-17 10:47 UTC, jon-betts commented on tests/h/presenters/annotation_searchindex_test.py
> +    @pytest.mark.usefixtures("factories")
```suggestion
```

2021-08-17 10:47 UTC, jon-betts commented on tests/h/schemas/forms/admin/group_test.py
> +@pytest.mark.usefixtures("factories")
```suggestion
```

2021-08-17 10:47 UTC, jon-betts commented on tests/h/search/query_test.py
> +    @pytest.mark.usefixtures("pyramid_request")
```suggestion
```
? Can't see why we'd need a request if we don't use it?

2021-08-19 11:27 UTC, jon-betts requested changes
Hi, sorry, I'm going to stop this review early again. I've gone through about 20% of it and so far every example of `@usefixtures` can be removed and the tests still pass.

I think we still have an unused argument here, it's just much harder to spot.

2021-08-19 11:27 UTC, jon-betts commented on tests/functional/api/test_moderation.py
> +@pytest.mark.usefixtures("user")
```suggestion
```

Test works without this I think

2021-08-19 11:27 UTC, jon-betts commented on tests/functional/api/test_moderation.py
> +@pytest.mark.usefixtures("user")
```suggestion
```

Same here

2021-08-19 11:27 UTC, jon-betts commented on tests/functional/api/test_profile.py
> +@pytest.mark.usefixtures("db_session")
```suggestion
```

2021-08-19 11:27 UTC, jon-betts commented on tests/functional/api/test_profile.py
> +    @pytest.mark.usefixtures("open_group")
```suggestion
```

2021-08-19 11:27 UTC, jon-betts commented on tests/functional/test_moderation.py
> +    @pytest.mark.usefixtures("group")
```suggestion
```

This ins included by pulling in the `flagged_annotation`

2021-08-19 11:27 UTC, jon-betts commented on tests/functional/test_oauth.py
> +    @pytest.mark.usefixtures("authclient", "userid")
```suggestion
```

2021-08-19 11:27 UTC, jon-betts commented on tests/functional/test_oauth.py
> +    @pytest.mark.usefixtures("authclient", "userid")
```suggestion
```

2021-08-19 11:27 UTC, jon-betts commented on tests/functional/test_oauth.py
> +    @pytest.mark.usefixtures("authclient", "userid")
```suggestion
```

2021-08-19 11:27 UTC, jon-betts commented on tests/functional/test_oauth.py
> +    @pytest.mark.usefixtures("authclient", "userid")
```suggestion
```

2021-08-19 11:27 UTC, jon-betts commented on tests/h/accounts/__init___test.py
> +    @pytest.mark.usefixtures("pyramid_config")
```suggestion
```

2021-08-19 11:27 UTC, jon-betts commented on tests/h/activity/query_test.py
> +    @pytest.mark.usefixtures("search")
```suggestion
```

2021-08-19 11:27 UTC, jon-betts commented on tests/h/activity/query_test.py
> +    @pytest.mark.usefixtures("search")
```suggestion
```

2021-08-19 11:27 UTC, jon-betts commented on tests/h/activity/query_test.py
> +    @pytest.mark.usefixtures("annotations", "group_pubids")
```suggestion
```

2021-08-19 11:27 UTC, jon-betts commented on tests/h/activity/query_test.py
> +    @pytest.mark.usefixtures("annotations")
```suggestion
```

2021-08-19 11:27 UTC, jon-betts commented on tests/h/activity/query_test.py
> +    @pytest.mark.usefixtures("annotations")
```suggestion
```

2021-08-19 13:36 UTC, marcospri commented on tests/h/views/activity_test.py
> +        self, controller, test_group, test_user, search
All of these "test_group, test_user" come from the `parametrize`

2021-08-20 12:23 UTC, jon-betts approved these changes
This was much easier to review this time. There are also some good fixes for some of the tests which weren't directly part of this, but improved it anyway.

The nice thing about this is it's gone from adding 100 lines to removing 60.

The one thing I'd say is I think the remaining use fixures can all be removed in favour of `autouse=True`. There are two reasons to do this:

* Every test in a class uses the fixture - This is the best possible reason
* The fixture is a patch - I'm less sure on this one. If you don't need it, don't patch it? But on the other hand if you aren't meant to call the real code, maybe do?

Of the remaining 4 or 5 usefixtures most fall into the first category, and a couple the second. At this point I'd say it's more style points. The fixture really is in use, so saying so isn't bad.

2021-08-20 12:23 UTC, jon-betts commented on tests/h/feeds/atom_test.py
> +    util.tag_uri_for_annotation.assert_called_once()
Seems like we cheated here a bit?

2021-08-20 12:23 UTC, jon-betts commented on tests/h/form_test.py
> +    @pytest.mark.usefixtures("Form")
As every test in this class uses `Form` it's probably a good case for `autouse=True`

2021-08-20 12:23 UTC, jon-betts commented on tests/h/security/test_acl.py
> +    def test_it_with_a_shared_annotation_with_no_group(self, annotation):
Oops, a bunch of this was me recently. Sorry!

2021-08-20 12:23 UTC, jon-betts commented on tests/h/services/list_organizations_test.py
> +    def test_returns_organizations_for_the_authority_specified(self, svc):
:+1: Even if these are for "noise" they are already auto-used so this was double pointless.

2021-08-20 12:23 UTC, jon-betts commented on tests/h/views/accounts_test.py
>      def test_post_generates_mail(
Holy crap. This test is 933 lines long! Fair enough the file it's testing is 633 so the ratio isn't bad, but this could do with splitting up a bit!

2021-08-20 12:23 UTC, jon-betts commented on tests/h/views/accounts_test.py
> +    @pytest.mark.usefixtures("ResetCode")
This one is a patch that would also be a good fit for an autouse

2021-08-20 12:23 UTC, jon-betts commented on tests/h/views/admin/groups_test.py
> +        self, pyramid_request, organization, AdminGroupSchema
:+1: I love it when this happens for some reason

2021-08-20 12:23 UTC, jon-betts commented on tests/h/views/admin/groups_test.py
>              return on_success(base_appstruct)
:( These tests are gross. But that's not what you're trying to fix

2021-08-20 12:23 UTC, jon-betts commented on tests/h/views/admin/organizations_test.py
> +    @pytest.mark.usefixtures("orgs")
Seeing as this fixture is defined for this one test, it's probably a good candidate for autouse.

2021-08-20 12:23 UTC, jon-betts commented on tests/h/views/admin/organizations_test.py
> -            )
... oh god why. Yeah good clean up here

2021-08-20 13:09 UTC, merged