Handle AnnotationSlim records form factories.Annotation
hypothesis/h pull request #8260
Opened 2023-10-16 13:31 UTC by marcospri

2023-10-16 13:38 UTC, marcospri commented on h/models/annotation_slim.py
> +        "Annotation", backref=sa.orm.backref("slim", uselist=False)
Added the backref here so annotation.slim is possible. Useful in the factories.

2023-10-16 13:38 UTC, marcospri commented on tests/common/factories/annotation.py
> +AUTHORITY = "localhost"
Move this to a constant instead of inlined in a lambda.

2023-10-16 13:38 UTC, marcospri commented on tests/common/factories/annotation.py
> +        if not create or not kwargs.get("new"):
I didn't know about the kwargs here, `name_of_method__anything` ends up here.

2023-10-16 13:38 UTC, marcospri commented on tests/common/factories/annotation.py
> +        if not create or not kwargs.get("new"):
This is opt-int, the whole test suite is very lax with integrity around groups, users. 

We can use it in more tests if we move into making the new table more useful.

2023-10-17 14:35 UTC, seanh requested changes
Hmm, I think it's best to keep factories nice and simple, and some of the ones in h including `factories.Annotation` are already quite complex.

If a test needs an `Annotation` with an `AnnotationSlim`, can it just call `factories.AnnotationSlim` instead of `factories.Annotation`? That will create both because `factories.AnnotationSlim` already has `factories.Annotation` as a `SubFactory`. I think this may be the simplest solution. In your other PR:

```diff
diff --git a/tests/functional/api/bulk/annotation_test.py b/tests/functional/api/bulk/annotation_test.py
index bcbaac27a..cd1e822b5 100644
--- a/tests/functional/api/bulk/annotation_test.py
+++ b/tests/functional/api/bulk/annotation_test.py
@@ -25,13 +25,12 @@ class TestBulkAnnotation:
             authority_provided_id="1234567890",
             members=[user],
         )
-        factories.Annotation(
-            userid=user.userid,
+        factories.AnnotationSlim(
+            user=user,
             group=group,
             shared=True,
             deleted=False,
             updated="2018-11-13T20:20:39",
-            slim__new=True,
         )
 
         response = make_request(
```

So you can do:

```python
annotation_slim = factories.AnnotationSlim()
annotation = annotation_slim.annotation
```

Or:

```
annotation = factories.AnnotationSlim().annotation
```

If you really want to be able to call `factories.Annotation()` and have an `AnnotationSlim` be created as well, it feels wrong to use `@factory.post_generation` to create an `AnnotationSlim` and `User` directly: I think this should be using `SubFactory` or `RelatedFactory`. It's tricky to get it to work for several reasons: 

* You don't want `factories.Annotation()` to create an `AnnotationSlim` by default, only sometimes. `SubFactory` and `RelatedFactory` work the other way round: they will be created by default and you have to disable it manually with `factories.Annotation(annotation_slim=None)`. I think this is telling us that the tests should be calling `factories.AnnotationSlim()` as suggsted above
* `AnnotationSlim.deleted`, `AnnotationSlim.shared`, `AnnotationSlim.group` and `AnnotationSlim.document` should all match their counterparts in `Annotation`. This is easy enough to do with `SelfAttribute`'s (see below)
* `AnnotationSlim.user` has to match the `user` of the annotation but this is a pain because there is no `Annotation.user` only `userid`, and because a user with this `userid` may or may not already exist in the DB. I partially solved this below but not really for the case when the user already exists
* `AnnotationSlim.created` and `updated` should match the ones in `Annotation` but this can't be implemented without fixing `factories.Annotation` first: `factories.Annotation.created` and `updated` aren't proper factory_boy fields, they're just added by a `@post_generation` hack

Whew, it ends up pretty complicated. Partially-working implementation below. But I think it's too complicated: I think the tests should call `factories.AnnotationSlim` when they want an `AnnotationSlim` to be created.

```diff
diff --git a/tests/common/factories/annotation.py b/tests/common/factories/annotation.py
index fd43fbec2..b0d406150 100644
--- a/tests/common/factories/annotation.py
+++ b/tests/common/factories/annotation.py
@@ -16,6 +16,13 @@ from .user import User
 AUTHORITY = "localhost"
 
 
+# FIXME: There must be an existing utility function for this somewhere?
+# Use it instead of duplicating this here.
+def username_from(userid):
+    """Return just the username part from `userid`."""
+    return userid.split("@")[0].split("acct:")[1]
+
+
 class Annotation(ModelFactory):
     class Meta:
         model = models.Annotation
@@ -33,6 +40,20 @@ class Annotation(ModelFactory):
     )
     document = factory.SubFactory(Document)
     groupid = "__world__"
+    annotation_slim = factory.RelatedFactory(
+        "tests.common.factories.annotation_slim.AnnotationSlim",
+        factory_related_name="annotation",
+        # FIXME: AnnotationSlim.created and AnnotationSlim.updated should also
+        # be SelfAttribute's but can't be because `created` and `updated`
+        # aren't normal factory_boy fields in factories.Annotation: they're
+        # added by an @post_generation hook.
+        deleted=factory.SelfAttribute("..deleted"),
+        shared=factory.SelfAttribute("..shared"),
+        document=factory.SelfAttribute("..document"),
+        group=factory.SelfAttribute("..group"),
+        # FIXME: Does this work correctly if the user already exists? Maybe?
+        user__username=factory.LazyAttribute(lambda annotation_slim: username_from(annotation_slim.factory_parent.annotation.userid)),
+    )
 
     @factory.lazy_attribute
     def target_selectors(self):
@@ -154,34 +175,3 @@ class Annotation(ModelFactory):
         # pylint:disable=attribute-defined-outside-init
         self.created = self.created or datetime.datetime.now()
         self.updated = self.updated or datetime.datetime.now()
-
-    @factory.post_generation
-    def slim(self, create, extracted, **kwargs):  # pylint:disable=unused-argument
-        if not create or not kwargs.get("new"):
-            # If strategy is not `create` or `slim_new` is not explicitly passed, stop here.
-            return
-
-        # pylint:disable=import-outside-toplevel, cyclic-import
-        from .annotation_slim import AnnotationSlim
-
-        username = self.userid.split("@")[0].split("acct:")[1]
-        db = orm.object_session(self)
-        user = (
-            db.query(models.User)
-            .filter_by(username=username, authority=AUTHORITY)
-            .one_or_none()
-        )
-        if not user:
-            user = User(username=username, authority=AUTHORITY)
-
-        AnnotationSlim(
-            created=self.created,
-            updated=self.updated,
-            shared=self.shared,
-            deleted=self.deleted,
-            moderated=False,
-            annotation=self,
-            group=self.group,
-            document_id=self.document_id,
-            user=user,
-        )
diff --git a/tests/functional/api/bulk/annotation_test.py b/tests/functional/api/bulk/annotation_test.py
index bcbaac27a..9bf59e2e1 100644
--- a/tests/functional/api/bulk/annotation_test.py
+++ b/tests/functional/api/bulk/annotation_test.py
@@ -31,7 +31,9 @@ class TestBulkAnnotation:
             shared=True,
             deleted=False,
             updated="2018-11-13T20:20:39",
-            slim__new=True,
+            # FIXME: If `created` and `updated` were implemented correctly in
+            # the RelatedFactory then you wouldn't need this here.
+            annotation_slim__updated="2018-11-13T20:20:39",
         )
 
         response = make_request(
```

2023-10-18 09:54 UTC, closed without merging