[WIP] Split queue and indexing responsibilities
hypothesis/h pull request #8347
Opened 2023-11-29 11:46 UTC by marcospri

Avoid one confusing level of indirection and duplicated code

2023-11-30 14:29 UTC, marcospri commented on h/services/job_queue/queue.py
> +    def queue_annotations_between_times(start_time, end_time, tag):
These don't add much but are easier to mock (instead of patching) via the mock service when used elsewhere.

2023-11-30 14:30 UTC, marcospri commented on h/services/nipsa.py
> -    # NipsaService uses a search_index getter function rather than the search
No need for any of this. No ES connection, we are only queuing the annotations in the postgres table.

2023-11-30 14:32 UTC, marcospri commented on h/services/search_index/_queue.py
>  class Queue:
This class is now about taking elements out of the queue to reindex them.

2023-11-30 14:33 UTC, marcospri commented on h/services/search_index/_queue.py
> -        if hide_scheduled:  # pragma: no cover
We never filter by these. Without a comment is weird to include them anyway and no-cover.

2023-11-30 14:34 UTC, marcospri commented on h/services/search_index/service.py
> +from h.tasks import indexer as indexer_tasks
I like having the explicit "tasks" here, it makes it more clear what we are actually doing below.

2023-11-30 14:35 UTC, marcospri commented on h/tasks/indexer.py
> -@celery.task
These task are not about indexing but about queuing.

2023-11-30 14:35 UTC, marcospri commented on h/tasks/queue.py
> +@celery.task
Task just about queueing here.

2023-11-30 14:40 UTC, marcospri commented on requirements/lint.txt
> +freezegun==1.2.2
I found this easier in general that mocking/patching datetime

2023-12-06 13:39 UTC, seanh requested changes
I think it's generally a good direction to move towards having a generic `JobQueueService` with generic methods for adding jobs of different types. This is how the job queue code always should have been designed, but we were misguidedly trying to "hide" the fact that we had a generic job queue from the services: hiding the queue inside `SearchIndexService` and now allowing a generic `JobQueueService`. This direction fixes that mis-design.

Various suggestions below

2023-12-13 11:35 UTC, marcospri commented on h/celery.py
> +        "h.tasks.queue.add_users_annotations": "indexer",
Yes, makes sense, renamed the module and the tasks :+1:

2023-12-13 11:36 UTC, marcospri commented on h/services/__init__.py
> +        "h.services.job_queue.queue.factory", iface=QueueService, name="queue_service"
I agree with this but I'd like to do this a separate commit that just does the renaming.

2023-12-13 11:38 UTC, marcospri commented on h/services/search_index/_queue.py
>  class Queue:
Yes makes sense, like but like the service rename I'd like to do this one a separate PR after this.

2023-12-13 11:39 UTC, marcospri commented on h/services/search_index/service.py
> +from h.tasks import indexer as indexer_tasks
Yeah, much better :+1:

2023-12-13 13:10 UTC, marcospri commented on h/services/job_queue/queue.py
> +    def queue_annotations_between_times(start_time, end_time, tag):
Gone for the route of calling the tasks directly.

A couple of services were also calling these but it's not a big deal. 

It's not the goal metric but this change reduced line count.

2023-12-13 13:10 UTC, marcospri commented on h/tasks/queue.py
> +@celery.task
Yes, my idea is to add that in a follow up, it will be easier to diff without this refactor out of the way.

2023-12-13 13:13 UTC, marcospri commented on h/services/job_queue/queue.py
> +    def get_jobs_from_queue(self, limit, name="sync_annotation"):
Done

2023-12-13 13:15 UTC, marcospri commented on h/services/job_queue/queue.py
> +            self._db.delete(job)
Done

2023-12-20 12:24 UTC, marcospri commented
Changed a few things here, the biggest removing the queueing methods from the service. The views now directly call the tasks.

I deferred some other refactors to later, more focused PRs.

2023-12-20 14:08 UTC, seanh approved these changes

2023-12-21 10:58 UTC, marcospri commented
I'm going to merge here some more refactor-like PRs and do a final round of testing before merging it to `main`.

2024-01-17 14:37 UTC, marcospri commented on h/services/search_index/_queue.py
>  class Queue:
Done

2024-01-17 14:50 UTC, marcospri commented on h/services/__init__.py
> +        "h.services.job_queue.queue.factory", iface=QueueService, name="queue_service"
Done

2024-01-18 09:14 UTC, merged